/**
 * generate.ts — Materialize every generated artifact this package
 * composes to real files under generated/, so the actual output (a C
 * header, TS declarations, and the literal compiled `encode`/`decode`
 * functions) can be opened and read directly — not just asserted against
 * in tests, or run without ever being seen. Run via `npm run generate`.
 */
import * as fs from "node:fs"
import * as path from "node:path"

import {cHeader, tsDeclarations, jsCodecModule} from "./compose"

const OUT_DIR = path.join(__dirname, "..", "generated")

const banner = (source: string): string =>
    `/* AUTO-GENERATED by \`npm run generate\` (packages/example/src/generate.ts) from schema.ts — do not edit by hand. */\n\n${source}`

const write = (file: string, content: string): void =>
{
    fs.writeFileSync(path.join(OUT_DIR, file), banner(content))
    console.log(`  ${file}`)
}

fs.mkdirSync(OUT_DIR, {recursive: true})
console.log(`Writing generated artifacts to ${OUT_DIR}:`)
write("telemetry-packet.h", cHeader)
write("telemetry-packet.d.ts", tsDeclarations)
write("telemetry-packet.codec.ts", jsCodecModule)
