#ifndef JIT_ARMV6M_BENCH_EXT_SAMPSTREAM_H_
#define JIT_ARMV6M_BENCH_EXT_SAMPSTREAM_H_

#include <cstdint>

/* Wire opcodes, sizes and buffers, mirrored in bench/sampstream_ext.ts,
 * which carries the specification. Sizes are powers of two so masking is
 * two shifts on a core with no AND-immediate. */

constexpr uint32_t SAMP_IN_BITS = 12;
constexpr uint32_t SAMP_OUT_BITS = 10;
constexpr uint32_t SAMP_EVENT_BITS = 5;

constexpr uint32_t SAMP_IN_SAMPLES = 1u << SAMP_IN_BITS;
constexpr uint32_t SAMP_OUT_SAMPLES = 1u << SAMP_OUT_BITS;
constexpr uint32_t SAMP_EVENTS = 1u << SAMP_EVENT_BITS;

constexpr uint32_t TRIGGER_KIND_BITS = 4;
constexpr uint32_t TRIGGER_MAX_KIND = (1u << TRIGGER_KIND_BITS) - 1;

constexpr uint8_t SAMPSTREAM_SAMPLE_AT = 0x80;
constexpr uint8_t SAMPSTREAM_OUT_AT = 0x81;
constexpr uint8_t SAMPSTREAM_TRIGGER = 0x82;

/* count first, so the entry array's offsets stay small enough for the
 * emitted `adds` that skips past it. Not masked: an overrun stays visible
 * instead of being indistinguishable from a full ring. */
struct SampEvents
{
    uint32_t count;
    uint32_t entries[SAMP_EVENTS];
};

/* Input lives in flash: it is read-only to a program, and 8KB of it would
 * not fit the model's RAM beside everything else. Generated by
 * bench/gen-programs.ts into generated/samples.cpp. */
extern const int16_t g_sampIn[SAMP_IN_SAMPLES];

extern int16_t g_sampOut[SAMP_OUT_SAMPLES];
extern SampEvents g_sampEvents;

/** Zeroed between runs — these are static and outlive one program. */
void sampStreamReset();

#endif // JIT_ARMV6M_BENCH_EXT_SAMPSTREAM_H_
