// Generates the acceptance-gate image's data and the reference results it
// will be checked against.
//
// One place decides what the program is, what samples it sees, and what the
// answer is: the reference VM. The target image is handed the first two as
// generated C++ and never told the third, so agreement is evidence rather
// than construction.
//
// Usage: npx ts-node --transpile-only bench/gen-check.ts <out-dir>

import {writeFileSync} from "node:fs"
import {proc, ir, lowerProgram, validateProgram, run, encodeJitProgram}
    from "../../packages/machine/src/index"
import {sampStreamExtension, SAMP_IN_SAMPLES, SAMP_OUT_SAMPLES, SAMP_EVENTS}
    from "./sampstream_ext"

const N = 512

/* Every op, in the shapes the emitters actually have to handle: a SAMPLE_AT
 * whose value must survive a sibling's evaluation (so one of the pair lands
 * at "tos"), an OUT_AT taking a computed index off the stack, and a TRIGGER
 * with a non-zero kind, which is the only path emitting the `adds`. The
 * loop runs long enough to wrap the event ring and to reach far enough into
 * the input window to exercise the mask. */
const body = ir`
u32 i = 0;
u32 s = 0;
while (i != n)
{
    s = sample_at(i) + sample_at(i - 1);
    out_at(i, s);
    if (s > 1000)
    {
        trigger(3, i);
    }
    i = i + 1;
}
return s;
`

/** Mirrors check_runner.cpp's outputHash: FNV-1a, byte-wise, little-endian. */
function outputHash(out: Int16Array): number
{
    let h = 2166136261 >>> 0

    for(let i = 0; i < SAMP_OUT_SAMPLES; i++)
    {
        const v = out[i]! & 0xffff

        h = Math.imul(h ^ (v & 0xff), 16777619) >>> 0
        h = Math.imul(h ^ ((v >> 8) & 0xff), 16777619) >>> 0
    }

    return h >>> 0
}

function samples(): Int16Array
{
    const s = new Int16Array(SAMP_IN_SAMPLES)

    /* Two tones plus a ramp: real negatives, real sign changes, and values
     * both sides of the threshold, so neither the LDRSH sign extension nor
     * the unsigned comparison can pass by accident. */
    for(let i = 0; i < s.length; i++)
    {
        s[i] = Math.round(2600 * Math.sin(i / 7) + 900 * Math.sin(i / 2.3)) - 400
    }

    return s
}

function cArray(name: string, type: string, values: ArrayLike<number>, perLine: number): string
{
    const rows: string[] = []

    for(let i = 0; i < values.length; i += perLine)
    {
        const row: string[] = []
        for(let j = i; j < Math.min(i + perLine, values.length); j++) row.push(String(values[j]))
        rows.push("    " + row.join(", "))
    }

    return `${type} ${name} = {\n${rows.join(",\n")}\n};\n`
}

function main(): void
{
    const outDir = process.argv[2]
    if(outDir === undefined) throw new Error("usage: gen-check.ts <out-dir>")

    const ext = sampStreamExtension()
    const input = samples()
    ext.input.set(input)

    const program = lowerProgram(proc(["n"], body), ext)
    const stats = validateProgram(program, ext)
    const envelope = encodeJitProgram(program, ext)

    const result = run(program, ext, [N])
    if(!result.ok) throw new Error(`reference VM trapped: ${result.trapCode}`)

    writeFileSync(`${outDir}/samples.cpp`,
        `/* Generated by bench/gen-check.ts — do not edit. */\n`
        + `#include "ext_sampstream.h"\n\n`
        + cArray("g_sampIn[SAMP_IN_SAMPLES]", "extern const int16_t", input, 16))

    writeFileSync(`${outDir}/check_data.h`,
        `/* Generated by bench/gen-check.ts — do not edit. */\n`
        + `#ifndef JIT_ARMV6M_BENCH_GENERATED_CHECK_DATA_H_\n`
        + `#define JIT_ARMV6M_BENCH_GENERATED_CHECK_DATA_H_\n\n`
        + `#include <stdint.h>\n\n`
        + `extern const uint8_t g_checkProgram[];\n`
        + `extern const uint32_t g_checkProgramLen;\n`
        + `extern const uint32_t g_checkArgs[];\n`
        + `extern const uint32_t g_checkArgCount;\n\n`
        + `#endif\n`)

    writeFileSync(`${outDir}/check_data.cpp`,
        `/* Generated by bench/gen-check.ts — do not edit. */\n`
        + `#include "generated/check_data.h"\n\n`
        + cArray("g_checkProgram[]", "extern const uint8_t", envelope, 16)
        + `\nextern const uint32_t g_checkProgramLen = ${envelope.length};\n`
        + `extern const uint32_t g_checkArgs[] = {${N}};\n`
        + `extern const uint32_t g_checkArgCount = 1;\n`)

    const expected = {
        acc: result.acc >>> 0,
        outputHash: outputHash(ext.output),
        eventCount: ext.eventCount(),
        events: [...ext.events].map(v => v >>> 0),
        envelopeBytes: envelope.length,
        totalDepth: stats.totalDepth,
        maxCallDepth: stats.maxCallDepth,
        samples: N,
        vmSteps: result.steps,
    }

    writeFileSync(`${outDir}/expected.json`, JSON.stringify(expected, null, 2) + "\n")

    if(expected.eventCount <= SAMP_EVENTS)
    {
        throw new Error(`the fixture triggers ${expected.eventCount} times and never wraps the `
            + `${SAMP_EVENTS}-entry ring — it is not exercising the wrap`)
    }

    console.log(`generated: envelope=${envelope.length}B acc=${expected.acc} `
        + `hash=${expected.outputHash.toString(16)} triggers=${expected.eventCount}`)
}

main()
