// Generates everything the benchmark image is built from, plus the results
// it will be checked against.
//
// One source of truth for each fact. The workload's thresholds are declared
// in workloads/*.ts and emitted as a header the compiled reference includes,
// so the two sides cannot drift apart silently — which they would the first
// time a threshold was tuned in one place. The expected answers come from
// the reference VM, and the image is never told them.
//
// Usage: npx ts-node --transpile-only bench/gen-bench.ts <out-dir>

import {writeFileSync} from "node:fs"
import {lowerProgram, validateProgram, run, encodeJitProgram, decodeLeb128}
    from "../../packages/machine/src/index"
import {sampStreamExtension, packEvent, SAMP_EVENTS, EVENT_MASK} from "./sampstream_ext"
import {BENCH_N0, BENCH_N1, BENCH_N2} from "./bench-config"
import {pulseTriggerProc, pulseTriggerSamples, pulseTriggerReference,
    HI, LO, MIN_WIDTH, MAX_WIDTH, TRIGGER_KIND} from "./workloads/pulse-trigger"

/** Mirrors bench_runner.cpp's eventHash: FNV-1a over the ring then the count. */
function eventHash(events: Uint32Array, count: number): number
{
    let h = 2166136261 >>> 0

    const words = [...events, count]
    for(const v of words)
    {
        for(let b = 0; b < 4; b++)
        {
            h = Math.imul(h ^ ((v >>> (8 * b)) & 0xff), 16777619) >>> 0
        }
    }

    return h >>> 0
}

function cArray(decl: string, values: ArrayLike<number>, perLine: number): string
{
    const rows: string[] = []

    for(let i = 0; i < values.length; i += perLine)
    {
        const row: string[] = []
        for(let j = i; j < Math.min(i + perLine, values.length); j++) row.push(String(values[j]))
        rows.push("    " + row.join(", "))
    }

    return `${decl} = {\n${rows.join(",\n")}\n};\n`
}

/** Where the procedure bodies start: past max_call_depth, total_depth and
 *  the procedure count, all LEB128 (jit-armv6m.ts's envelope). */
function bodyOffset(envelope: Uint8Array): {offset: number; procCount: number}
{
    let pos = 0
    pos = decodeLeb128(envelope, pos).next
    pos = decodeLeb128(envelope, pos).next

    const procs = decodeLeb128(envelope, pos)
    return {offset: procs.next, procCount: procs.value}
}

const GENERATED = "/* Generated by bench/gen-bench.ts — do not edit. */\n"

function main(): void
{
    const outDir = process.argv[2]
    if(outDir === undefined) throw new Error("usage: gen-bench.ts <out-dir>")

    const ext = sampStreamExtension()
    const input = pulseTriggerSamples()
    ext.input.set(input)

    const program = lowerProgram(pulseTriggerProc(), ext)
    const stats = validateProgram(program, ext)
    const envelope = encodeJitProgram(program, ext)
    const {offset, procCount} = bodyOffset(envelope)

    /* The image runs the phases in order and hashes after the last one, so
     * the expected hash is the one for BENCH_N2 from a fresh ring. */
    ext.reset()
    const result = run(program, ext, [BENCH_N2], 100_000_000)
    if(!result.ok) throw new Error(`reference VM trapped: ${result.trapCode}`)

    const wantEvents = new Uint32Array(SAMP_EVENTS)
    let wantCount = 0

    const wantAcc = pulseTriggerReference(input, BENCH_N2, index =>
    {
        wantEvents[wantCount & EVENT_MASK] = packEvent(index, TRIGGER_KIND)
        wantCount++
    })

    /* Three independent routes to the same answer — the DSL through the VM,
     * the TypeScript transcription, and (on the target) the emitted Thumb
     * and the compiled reference. Two of them are checked here so the image
     * only ever has to confirm the third and fourth. */
    if(result.acc !== wantAcc)
    {
        throw new Error(`the VM returned ${result.acc} where the transcription returned ${wantAcc}`)
    }

    if(ext.eventCount() !== wantCount)
    {
        throw new Error(`the VM triggered ${ext.eventCount()} times, the transcription ${wantCount}`)
    }

    writeFileSync(`${outDir}/samples.cpp`,
        GENERATED + `#include "ext_sampstream.h"\n\n`
        + cArray("extern const int16_t __attribute__((section(\".samples\"))) "
            + "g_sampIn[SAMP_IN_SAMPLES]", input, 16))

    writeFileSync(`${outDir}/workload_params.h`,
        GENERATED
        + `#ifndef JIT_ARMV6M_BENCH_GENERATED_WORKLOAD_PARAMS_H_\n`
        + `#define JIT_ARMV6M_BENCH_GENERATED_WORKLOAD_PARAMS_H_\n\n`
        + `/* Declared in bench/workloads/pulse-trigger.ts, which is where they\n`
        + ` * are baked into the DSL body too — the point of generating them is\n`
        + ` * that the two sides cannot be tuned apart. */\n`
        + `#define PULSE_HI ${HI}u\n`
        + `#define PULSE_LO ${LO}u\n`
        + `#define PULSE_MIN_WIDTH ${MIN_WIDTH}u\n`
        + `#define PULSE_MAX_WIDTH ${MAX_WIDTH}u\n`
        + `#define PULSE_TRIGGER_KIND ${TRIGGER_KIND}u\n\n`
        + `#endif\n`)

    writeFileSync(`${outDir}/bench_data.h`,
        GENERATED
        + `#ifndef JIT_ARMV6M_BENCH_GENERATED_BENCH_DATA_H_\n`
        + `#define JIT_ARMV6M_BENCH_GENERATED_BENCH_DATA_H_\n\n`
        + `#include <stdint.h>\n\n`
        + `#define BENCH_N0 ${BENCH_N0}u\n`
        + `#define BENCH_N1 ${BENCH_N1}u\n`
        + `#define BENCH_N2 ${BENCH_N2}u\n`
        + `#define BENCH_PROC_COUNT ${procCount}u\n`
        + `#define BENCH_BODY_OFFSET ${offset}u\n\n`
        + `extern const uint8_t g_benchProgram[];\n`
        + `extern const uint32_t g_benchProgramLen;\n\n`
        + `#endif\n`)

    writeFileSync(`${outDir}/bench_data.cpp`,
        GENERATED + `#include "generated/bench_data.h"\n\n`
        + cArray("extern const uint8_t g_benchProgram[]", envelope, 16)
        + `\nextern const uint32_t g_benchProgramLen = ${envelope.length};\n`)

    const expected = {
        workload: "pulse-trigger",
        n0: BENCH_N0,
        n1: BENCH_N1,
        n2: BENCH_N2,
        result: wantAcc >>> 0,
        eventHash: eventHash(wantEvents, wantCount),
        eventCount: wantCount,
        bytecodeBytes: envelope.length,
        totalDepth: stats.totalDepth,
        maxCallDepth: stats.maxCallDepth,
        procCount,
        vmSteps: result.steps,
    }

    writeFileSync(`${outDir}/bench_expected.json`, JSON.stringify(expected, null, 2) + "\n")

    console.log(`generated: bytecode=${envelope.length}B procs=${procCount} `
        + `totalDepth=${stats.totalDepth} triggers=${wantCount} `
        + `hash=0x${expected.eventHash.toString(16)}`)
}

main()
