// Generates everything one workload's benchmark image is built from, plus
// the results it will be checked against.
//
// One source of truth for each fact. Every workload's parameters are
// declared in workloads/*.ts and emitted as a header the compiled reference
// includes, so the two sides cannot drift apart silently — which they would
// the first time a threshold was tuned in one place. The expected answers
// come from the reference VM, and the image is never told them.
//
// Usage: npx ts-node --transpile-only bench/gen-bench.ts <out-dir> <workload>

import {writeFileSync} from "node:fs"
import {lowerProgram, validateProgram, run, encodeJitProgram, decodeLeb128}
    from "../../packages/machine/src/index"
import {sampStreamExtension, packEvent, SAMP_EVENTS, SAMP_OUT_SAMPLES,
    OUT_MASK, EVENT_MASK} from "./sampstream_ext"
import {BENCH_N0, BENCH_N1, BENCH_N2} from "./bench-config"
import {WORKLOADS, workloadNamed} from "./workloads/index"

/** Mirrors bench_runner.cpp's stateHash: FNV-1a over the output stream,
 *  then the event ring, then the count. Everything a workload can touch,
 *  so one number covers a filter and a trigger alike. */
function stateHash(out: Int16Array, events: Uint32Array, count: number): number
{
    let h = 2166136261 >>> 0

    const byte = (v: number): void => {h = Math.imul(h ^ (v & 0xff), 16777619) >>> 0}

    for(let i = 0; i < SAMP_OUT_SAMPLES; i++)
    {
        const v = out[i]! & 0xffff
        byte(v)
        byte(v >> 8)
    }

    for(const v of [...events, count])
    {
        for(let b = 0; b < 4; b++) byte(v >>> (8 * b))
    }

    return h >>> 0
}

function cArray(decl: string, values: ArrayLike<number>, perLine: number): string
{
    const rows: string[] = []

    for(let i = 0; i < values.length; i += perLine)
    {
        const row: string[] = []
        for(let j = i; j < Math.min(i + perLine, values.length); j++) row.push(String(values[j]))
        rows.push("    " + row.join(", "))
    }

    return `${decl} = {\n${rows.join(",\n")}\n};\n`
}

/** Where the procedure bodies start: past max_call_depth, total_depth and
 *  the procedure count, all LEB128 (jit-armv6m.ts's envelope). */
function bodyOffset(envelope: Uint8Array): {offset: number; procCount: number}
{
    let pos = 0
    pos = decodeLeb128(envelope, pos).next
    pos = decodeLeb128(envelope, pos).next

    const procs = decodeLeb128(envelope, pos)
    return {offset: procs.next, procCount: procs.value}
}

const GENERATED = "/* Generated by bench/gen-bench.ts — do not edit. */\n"

function main(): void
{
    const [outDir, name] = process.argv.slice(2)
    if(outDir === undefined || name === undefined)
    {
        throw new Error("usage: gen-bench.ts <out-dir> <workload>")
    }

    const workload = workloadNamed(name)

    const ext = sampStreamExtension()
    const input = workload.samples()
    ext.input.set(input)

    const program = lowerProgram(workload.proc(), ext)
    const stats = validateProgram(program, ext)
    const envelope = encodeJitProgram(program, ext)
    const {offset, procCount} = bodyOffset(envelope)

    /* The image runs its phases in order and hashes after the last one, so
     * the expected state is the one for BENCH_N2 from a fresh start. */
    ext.reset()
    const result = run(program, ext, [BENCH_N2], 200_000_000)
    if(!result.ok) throw new Error(`${name}: reference VM trapped: ${result.trapCode}`)

    const wantOut = new Int16Array(SAMP_OUT_SAMPLES)
    const wantEvents = new Uint32Array(SAMP_EVENTS)
    let wantCount = 0

    const wantAcc = workload.reference(input, BENCH_N2, {
        trigger(index, kind)
        {
            wantEvents[wantCount & EVENT_MASK] = packEvent(index, kind)
            wantCount++
        },
        out(index, value)
        {
            wantOut[index & OUT_MASK] = value
        },
    })

    /* Two independent routes to the same answer are checked here — the DSL
     * through the VM, and the TypeScript transcription — so the image only
     * has to confirm the third and fourth, the emitted Thumb and the
     * compiled reference. */
    if(result.acc !== wantAcc)
    {
        throw new Error(`${name}: the VM returned ${result.acc} where the transcription `
            + `returned ${wantAcc}`)
    }

    const wantHash = stateHash(wantOut, wantEvents, wantCount)
    const vmHash = stateHash(ext.output, ext.events, ext.eventCount())

    if(wantHash !== vmHash)
    {
        throw new Error(`${name}: the VM and the transcription disagree about what the `
            + `program wrote (0x${vmHash.toString(16)} vs 0x${wantHash.toString(16)})`)
    }

    /* Every image compiles every kernel, so the parameter header carries
     * all of them and only REF_KERNEL says which one this image measures. */
    const defines = WORKLOADS.flatMap(w =>
        Object.entries(w.params).map(([k, v]) => `#define ${k} ${v}u`)).join("\n")

    writeFileSync(`${outDir}/samples.cpp`,
        GENERATED + `#include "ext_sampstream.h"\n\n`
        + cArray(`extern const int16_t __attribute__((section(".samples"))) `
            + `g_sampIn[SAMP_IN_SAMPLES]`, input, 16))

    writeFileSync(`${outDir}/workload_params.h`,
        GENERATED
        + `#ifndef JIT_ARMV6M_BENCH_GENERATED_WORKLOAD_PARAMS_H_\n`
        + `#define JIT_ARMV6M_BENCH_GENERATED_WORKLOAD_PARAMS_H_\n\n`
        + `/* Declared in bench/workloads/*.ts, which is where they are baked\n`
        + ` * into the DSL bodies too — the point of generating them is that\n`
        + ` * the two sides cannot be tuned apart. */\n`
        + `${defines}\n\n`
        + `#endif\n`)

    writeFileSync(`${outDir}/bench_data.h`,
        GENERATED
        + `#ifndef JIT_ARMV6M_BENCH_GENERATED_BENCH_DATA_H_\n`
        + `#define JIT_ARMV6M_BENCH_GENERATED_BENCH_DATA_H_\n\n`
        + `#include <stdint.h>\n`
        + `#include "kernels_ref.h"\n\n`
        + `#define BENCH_WORKLOAD "${workload.name}"\n`
        + `#define BENCH_N0 ${BENCH_N0}u\n`
        + `#define BENCH_N1 ${BENCH_N1}u\n`
        + `#define BENCH_N2 ${BENCH_N2}u\n`
        + `#define BENCH_PROC_COUNT ${procCount}u\n`
        + `#define BENCH_BODY_OFFSET ${offset}u\n`
        + `#define REF_KERNEL ${workload.kernel}\n\n`
        + `extern const uint8_t g_benchProgram[];\n`
        + `extern const uint32_t g_benchProgramLen;\n\n`
        + `#endif\n`)

    writeFileSync(`${outDir}/bench_data.cpp`,
        GENERATED + `#include "generated/bench_data.h"\n\n`
        + cArray("extern const uint8_t g_benchProgram[]", envelope, 16)
        + `\nextern const uint32_t g_benchProgramLen = ${envelope.length};\n`)

    const expected = {
        workload: workload.name,
        kernel: workload.kernel,
        n0: BENCH_N0,
        n1: BENCH_N1,
        n2: BENCH_N2,
        result: wantAcc >>> 0,
        stateHash: wantHash,
        eventCount: wantCount,
        bytecodeBytes: envelope.length,
        totalDepth: stats.totalDepth,
        maxCallDepth: stats.maxCallDepth,
        procCount,
        vmSteps: result.steps,
    }

    writeFileSync(`${outDir}/${workload.name}_expected.json`,
        JSON.stringify(expected, null, 2) + "\n")

    console.log(`generated ${workload.name}: bytecode=${envelope.length}B `
        + `totalDepth=${stats.totalDepth} triggers=${wantCount} `
        + `hash=0x${wantHash.toString(16)}`)
}

main()
