/**
 * @ppl/machine/test — Generic extension hook (ROADMAP.md item 6)
 *
 * Exercises the `Extension` object threaded through every core stage using
 * a toy opcode, `double(x)` → `EXT DOUBLE_REG [regIndex]`: doubles a local
 * variable's value into `acc`. Not a real extension (that's the codec
 * extension, ROADMAP.md item 7, docs/codec-extension.md) — just
 * enough to prove the hook itself works end to end, and that every stage
 * still behaves exactly as before when no extension is registered.
 */

import { describe, test } from "node:test"
import assert from "node:assert/strict"

import { ir, proc } from "../src/ir"
import { lowerProgram } from "../src/lower"
import { validateProgram } from "../src/validate"
import { run } from "../src/vm"
import { encodeInstr, encodeBody, decodeBody, encodeLeb128, decodeLeb128 } from "../src/bytecode"
import { rule, leafNode } from "../src/rules"
import { pBuiltinCall, pIdentifier } from "../src/matcher"
import { extInstr, bare, brTable, CONST, PUSH, opRegWriteback } from "../src/rtl"
import type { RtlProgram, RtlInstr } from "../src/rtl"
import type { Extension } from "../src/extension"

function doubleExtension(): Extension
{
    return {
        rules: resolveLocal => [
            rule("ext:double", pBuiltinCall("double", pIdentifier()), m =>
                leafNode(["acc"], [extInstr("DOUBLE_REG", [resolveLocal(m.argumentMatches[0].name)])], [], 0, 0)),
        ],
        effects: { DOUBLE_REG: { tosDelta: 0, maxTransient: 0, writesAcc: true } },
        exec: (instr, state) => { state.acc = (state.reg(instr.operands[0]!) * 2) >>> 0 },
        codec: {
            encode: instr => [128, ...encodeLeb128(instr.operands[0]!)],
            decode: (bytes, offset) =>
            {
                const r = decodeLeb128(bytes, offset + 1)
                return { instr: extInstr("DOUBLE_REG", [r.value]), next: r.next }
            },
        },
    }
}

describe("extension hook — end to end via a toy `double(x)` opcode", () =>
{
    test("lowers through the DSL, validates, and executes", () =>
    {
        const ext = doubleExtension()
        const entry = proc([], ir`u32 x = 21; return double(x);`)

        const program = lowerProgram(entry, ext)
        const stats = validateProgram(program, ext)
        assert.equal(stats.procedures.length, 1)

        const result = run(program, ext)
        assert.equal(result.ok, true)
        assert.equal(result.acc, 42)
    })

    test("round-trips through the wire codec", () =>
    {
        const ext = doubleExtension()
        const instr = extInstr("DOUBLE_REG", [3])

        const bytes = encodeBody([instr], ext)
        assert.deepEqual([...bytes], [128, 3])
        assert.deepEqual(decodeBody(bytes, ext), [instr])
    })
})

/**
 * Toy call-shaped opcode, `EXT EXT_CALL [calleeIndex]`: actually invokes
 * `calleeIndex` via `ExecState.callProc` — the capability `vm.ts`'s `EXT`
 * case didn't expose until now. Exercises the one part `double(x)` above
 * never touches: a call-shaped extension op that both `validate.ts` (via
 * `effect.calleeOf`) and `vm.ts` (via `callProc`) treat as a real call
 * site — the mechanism `CALL_CODEC` (docs/codec-extension.md §3.3) will
 * need.
 *
 * No `rules()`/DSL surface here deliberately: referencing another
 * `Procedure` from inside `ir\`...\`` text only works in *callee* position
 * (`${proc}(...)`, `pCall()`'s own shape) — `matchAllEast`'s `"Call"` case
 * eagerly tiles every *argument* of any call-shaped node, for every rule
 * that might match it, before any rule's own `resolveCallee` check runs;
 * an argument that's a bare reference to another procedure (not a
 * declared local) has no viable tiling and `RegAlloc.resolveLocal` hard-
 * throws on it by design (lower.ts) — consistent with this codebase's
 * fail-fast style for what it treats as a genuine authoring bug. So a
 * call-shaped op whose *target* procedure is itself the reference (as
 * `CALL_CODEC` needs) is built directly at the `RtlProgram` level here,
 * matching how the codec extension's real procedures will be built too:
 * generated by a metaprogramming layer walking a type graph, not authored
 * as hand-typed `ir` text (docs/codec-extension.md §5).
 */
function callShapedExtension(): Extension
{
    return {
        // writesAcc, because exec below really does write acc: without it the
        // validator has no way to know, and the entry procedure's
        // `EXT_CALL; RETURN` reads an acc it believes nothing established
        // (a zero-argument procedure's entry doesn't — isa-core.md §4.6).
        effects: { EXT_CALL: { tosDelta: 0, maxTransient: 0, writesAcc: true, calleeOf: instr => instr.operands[0] } },
        exec: (instr, state) => { state.acc = state.callProc(instr.operands[0]!, []) },
    }
}

describe("extension hook — a call-shaped op actually invokes its callee", () =>
{
    test("validates (folded into the call graph) and executes the nested call", () =>
    {
        const ext = callShapedExtension()
        const program: RtlProgram = {
            procedures: [
                { argCount: 0, body: [extInstr("EXT_CALL", [1]), bare("RETURN")] }, // entry: ext_call(helper)
                { argCount: 0, body: [{ op: "CONST", imm: 99 }, bare("RETURN")] }, // helper: return 99;
            ],
        }

        const stats = validateProgram(program, ext)
        assert.equal(stats.totalDepth, 0) // neither procedure ever pushes to TOS

        const result = run(program, ext)
        assert.equal(result.ok, true)
        assert.equal(result.acc, 99) // proves callProc's return value actually reaches EXT_CALL's acc
    })
})

describe("extension hook — absent extension leaves every stage unaffected", () =>
{
    test("an EXT instruction with no matching effect declaration is rejected by the validator", () =>
    {
        const program: RtlProgram = { procedures: [{ argCount: 0, body: [extInstr("UNKNOWN", []), bare("RETURN")] }] }
        assert.throws(() => validateProgram(program), /no effect declaration registered/)
    })

    test("an EXT instruction with no registered exec throws at VM runtime", () =>
    {
        const program: RtlProgram = { procedures: [{ argCount: 0, body: [extInstr("DOUBLE_REG", [0]), bare("RETURN")] }] }
        assert.throws(() => run(program), /no extension registered to execute it/)
    })

    test("encoding an EXT instruction with no registered codec throws", () =>
    {
        assert.throws(() => encodeInstr(extInstr("DOUBLE_REG", [0])), /no registered extension codec/)
    })

    test("decoding an extension opcode byte with no registered codec throws", () =>
    {
        assert.throws(() => decodeBody(Uint8Array.from([128, 3])), /no extension mechanism registered/)
    })
})

describe("Procedure/RtlProc header — opaque data, untouched by the core", () =>
{
    test("carried through lowering unchanged", () =>
    {
        const header = { abiKind: "CODEC_ENCODER" }
        const entry = proc([], ir`return 1;`, { header })

        const program = lowerProgram(entry)
        assert.equal(program.procedures[0]!.header, header)
    })
})

/* ── validate.ts and vm.ts must agree about acc across an EXT op ────────
 *
 * Both halves read `readsAcc`/`writesAcc`; for a while only validate.ts
 * did, so a program it accepted threw at run time instead. The shape below
 * is what the codec extension's bitmap packing really emits: a write-back-
 * in-place combo poisons acc, an EXT op that declares `writesAcc`
 * re-establishes it, and the next instruction reads it.
 */
function accExtension(): Extension
{
    return {
        effects: {
            PRODUCE: { tosDelta: 0, maxTransient: 0, writesAcc: true },
            CONSUME: { tosDelta: 0, maxTransient: 0, readsAcc: true },
            OPAQUE:  { tosDelta: 0, maxTransient: 0 },
        },
        exec: (instr, state) =>
        {
            if(instr.ext === "PRODUCE") state.acc = 7
            else if(instr.ext === "CONSUME") state.setReg(0, state.acc)
        },
    }
}

describe("extension hook — acc liveness agrees between validate.ts and vm.ts", () =>
{
    // PUSH needs something live to push, so every program here opens with
    // a CONST; the poisoning is done by the REG_REG combo that follows.
    const prelude = [CONST(1), PUSH(), CONST(2), opRegWriteback("OR", 0)] as const

    test("a writesAcc op revives acc for a later read — validator and VM both", () =>
    {
        const program: RtlProgram = {
            procedures: [{ argCount: 0, body: [...prelude, extInstr("PRODUCE", []), bare("RETURN")] }],
        }
        const ext = accExtension()
        assert.doesNotThrow(() => validateProgram(program, ext))
        const r = run(program, ext)
        assert.equal(r.ok, true)
        assert.equal(r.acc, 7)
    })

    test("an opaque op does not revive acc — both halves still reject the read", () =>
    {
        const program: RtlProgram = {
            procedures: [{ argCount: 0, body: [...prelude, extInstr("OPAQUE", []), PUSH(), CONST(0), bare("RETURN")] }],
        }
        const ext = accExtension()
        assert.throws(() => validateProgram(program, ext), /read of acc/)
        assert.throws(() => run(program, ext), /read of acc/)
    })

    test("a readsAcc op on a poisoned acc is rejected by the VM, not just the validator", () =>
    {
        const program: RtlProgram = {
            procedures: [{ argCount: 0, body: [...prelude, extInstr("CONSUME", []), CONST(0), bare("RETURN")] }],
        }
        const ext = accExtension()
        assert.throws(() => validateProgram(program, ext), /EXT CONSUME/)
        assert.throws(() => run(program, ext), /EXT CONSUME/)
    })

    test("readsAcc is satisfied by a writesAcc op right before it", () =>
    {
        const program: RtlProgram = {
            procedures: [{ argCount: 0, body: [...prelude, extInstr("PRODUCE", []), extInstr("CONSUME", []), CONST(0), bare("RETURN")] }],
        }
        const ext = accExtension()
        assert.doesNotThrow(() => validateProgram(program, ext))
        assert.equal(run(program, ext).ok, true)
    })
})

/* ── isa-core.md §11.2's third direction: an op that destroys acc ───────
 *
 * MEMMOVE's shape (jit-armv6m/fuzz/rawmem_ext.ts): every operand goes off
 * the stack into a helper's argument registers, acc's own among them, so
 * nothing readable is left behind. The reference `exec` simply doesn't
 * touch acc — the declaration is what makes both halves agree that a read
 * after it is not a legal program.
 */
function killAccExtension(): Extension
{
    return {
        effects: {
            KILL:   { tosDelta: 0, maxTransient: 0, killsAcc: true },
            REVIVE: { tosDelta: 0, maxTransient: 0, writesAcc: true },
        },
        exec: (instr, state) => { if(instr.ext === "REVIVE") state.acc = 9 },
    }
}

describe("extension hook — killsAcc, an op that destroys acc", () =>
{
    test("a kill leaves acc dead — the RETURN after it is rejected by both halves", () =>
    {
        const program: RtlProgram = {
            procedures: [{ argCount: 0, body: [CONST(1), extInstr("KILL", []), PUSH(), CONST(0), bare("RETURN")] }],
        }
        const ext = killAccExtension()
        assert.throws(() => validateProgram(program, ext), /read of acc/)
        assert.throws(() => run(program, ext), /read of acc/)
    })

    test("re-establishing acc after a kill is legal and runs", () =>
    {
        const program: RtlProgram = {
            procedures: [{ argCount: 0, body: [CONST(1), extInstr("KILL", []), CONST(5), bare("RETURN")] }],
        }
        const ext = killAccExtension()
        assert.doesNotThrow(() => validateProgram(program, ext))
        assert.equal(run(program, ext).acc, 5)
    })

    test("a writesAcc op re-establishes what a kill destroyed", () =>
    {
        const program: RtlProgram = {
            procedures: [{ argCount: 0, body: [CONST(1), extInstr("KILL", []), extInstr("REVIVE", []), bare("RETURN")] }],
        }
        const ext = killAccExtension()
        assert.doesNotThrow(() => validateProgram(program, ext))
        assert.equal(run(program, ext).acc, 9)
    })

    test("a kill in one dispatch case kills the merge (isa-core.md §8.7)", () =>
    {
        const cases = (tail: RtlInstr[]): RtlInstr[] => [
            CONST(0), brTable(1),
            CONST(1), bare("BLOCK_END"),
            CONST(2), extInstr("KILL", []), bare("BLOCK_END"),
            ...tail,
        ]
        const ext = killAccExtension()

        assert.throws(() => validateProgram({ procedures: [{ argCount: 0, body: cases([PUSH(), CONST(0), bare("RETURN")]) }] }, ext), /read of acc/)
        assert.doesNotThrow(() =>
            validateProgram({ procedures: [{ argCount: 0, body: cases([CONST(3), bare("RETURN")]) }] }, ext))
    })

    test("writesAcc and killsAcc together is a declaration error, not a program one", () =>
    {
        const ext: Extension = {
            effects: { BOTH: { tosDelta: 0, maxTransient: 0, writesAcc: true, killsAcc: true } },
            exec: () => {},
        }
        const program: RtlProgram = {
            procedures: [{ argCount: 0, body: [CONST(1), extInstr("BOTH", []), bare("RETURN")] }],
        }
        assert.throws(() => validateProgram(program, ext), /both writesAcc and killsAcc/)
        assert.throws(() => run(program, ext), /both writesAcc and killsAcc/)
    })
})

/* ── the declaration is checked against what `exec` really does ─────────
 *
 * `ExecState.acc` is an accessor pair, so vm.ts sees every acc read and
 * write an extension makes and holds it to its own effect declaration —
 * the reference-side counterpart of the post-emit acc check jit-armv6m
 * runs on an extension's emitted code.
 */
describe("extension hook — vm.ts holds exec to its own acc declaration", () =>
{
    const program: RtlProgram = {
        procedures: [{ argCount: 0, body: [CONST(1), extInstr("OP", []), CONST(0), bare("RETURN")] }],
    }
    const withOp = (effect: NonNullable<Extension["effects"]>[string], exec: NonNullable<Extension["exec"]>): Extension =>
        ({ effects: { OP: effect }, exec })

    test("a write with no writesAcc is caught", () =>
        assert.throws(() => run(program, withOp({ tosDelta: 0, maxTransient: 0 }, (_i, s) => { s.acc = 3 })),
            /without declaring writesAcc/))

    test("a read with no readsAcc is caught", () =>
        assert.throws(() => run(program, withOp({ tosDelta: 0, maxTransient: 0 }, (_i, s) => { s.setReg(0, s.acc) })),
            /without declaring readsAcc/))

    test("writesAcc with nothing assigned is caught", () =>
        assert.throws(() => run(program, withOp({ tosDelta: 0, maxTransient: 0, writesAcc: true }, () => {})),
            /left acc unassigned/))

    test("a killsAcc op that assigns acc anyway is caught", () =>
        assert.throws(() => run(program, withOp({ tosDelta: 0, maxTransient: 0, killsAcc: true }, (_i, s) => { s.acc = 3 })),
            /without declaring writesAcc/))

    test("an exec-only extension keeps the unchecked path", () =>
        assert.equal(run(program, { exec: (_i, s) => { s.acc = 3 } }).ok, true))
})
