/**
 * @ppl/machine/test — Generic extension hook (ROADMAP.md item 6)
 *
 * Exercises the `Extension` object threaded through every core stage using
 * a toy opcode, `double(x)` → `EXT DOUBLE_REG [regIndex]`: doubles a local
 * variable's value into `acc`. Not a real extension (that's the codec
 * extension, ROADMAP.md item 7, docs/codec-extension.md) — just
 * enough to prove the hook itself works end to end, and that every stage
 * still behaves exactly as before when no extension is registered.
 */

import { describe, test } from "node:test"
import assert from "node:assert/strict"

import { ir, proc } from "../src/ir"
import { lowerProgram } from "../src/lower"
import { validateProgram } from "../src/validate"
import { run } from "../src/vm"
import { encodeInstr, encodeBody, decodeBody, encodeLeb128, decodeLeb128 } from "../src/bytecode"
import { rule, leafNode } from "../src/rules"
import { pBuiltinCall, pIdentifier } from "../src/matcher"
import { extInstr, bare } from "../src/rtl"
import type { RtlProgram } from "../src/rtl"
import type { Extension } from "../src/extension"

function doubleExtension(): Extension
{
    return {
        rules: resolveLocal => [
            rule("ext:double", pBuiltinCall("double", pIdentifier()), m =>
                leafNode(["acc"], [extInstr("DOUBLE_REG", [resolveLocal(m.argumentMatches[0].name)])], [], 0, 0)),
        ],
        effects: { DOUBLE_REG: { tosDelta: 0, maxTransient: 0 } },
        exec: (instr, state) => { state.acc = (state.reg(instr.operands[0]!) * 2) >>> 0 },
        codec: {
            encode: instr => [128, ...encodeLeb128(instr.operands[0]!)],
            decode: (bytes, offset) =>
            {
                const r = decodeLeb128(bytes, offset + 1)
                return { instr: extInstr("DOUBLE_REG", [r.value]), next: r.next }
            },
        },
    }
}

describe("extension hook — end to end via a toy `double(x)` opcode", () =>
{
    test("lowers through the DSL, validates, and executes", () =>
    {
        const ext = doubleExtension()
        const entry = proc([], ir`u32 x = 21; return double(x);`)

        const program = lowerProgram(entry, ext)
        const stats = validateProgram(program, ext)
        assert.equal(stats.procedures.length, 1)

        const result = run(program, ext)
        assert.equal(result.ok, true)
        assert.equal(result.acc, 42)
    })

    test("round-trips through the wire codec", () =>
    {
        const ext = doubleExtension()
        const instr = extInstr("DOUBLE_REG", [3])

        const bytes = encodeBody([instr], ext)
        assert.deepEqual([...bytes], [128, 3])
        assert.deepEqual(decodeBody(bytes, ext), [instr])
    })
})

/**
 * Toy call-shaped opcode, `EXT EXT_CALL [calleeIndex]`: actually invokes
 * `calleeIndex` via `ExecState.callProc` — the capability `vm.ts`'s `EXT`
 * case didn't expose until now. Exercises the one part `double(x)` above
 * never touches: a call-shaped extension op that both `validate.ts` (via
 * `effect.call`) and `vm.ts` (via `callProc`) treat as a real call site —
 * the mechanism `CALL_CODEC` (docs/codec-extension.md §3.3) will need.
 *
 * No `rules()`/DSL surface here deliberately: referencing another
 * `Procedure` from inside `ir\`...\`` text only works in *callee* position
 * (`${proc}(...)`, `pCall()`'s own shape) — `matchAllEast`'s `"Call"` case
 * eagerly tiles every *argument* of any call-shaped node, for every rule
 * that might match it, before any rule's own `resolveCallee` check runs;
 * an argument that's a bare reference to another procedure (not a
 * declared local) has no viable tiling and `RegAlloc.resolveLocal` hard-
 * throws on it by design (lower.ts) — consistent with this codebase's
 * fail-fast style for what it treats as a genuine authoring bug. So a
 * call-shaped op whose *target* procedure is itself the reference (as
 * `CALL_CODEC` needs) is built directly at the `RtlProgram` level here,
 * matching how the codec extension's real procedures will be built too:
 * generated by a metaprogramming layer walking a type graph, not authored
 * as hand-typed `ir` text (docs/codec-extension.md §5).
 */
function callShapedExtension(): Extension
{
    return {
        effects: { EXT_CALL: { tosDelta: 0, maxTransient: 0, call: { calleeOperandIndex: 0 } } },
        exec: (instr, state) => { state.acc = state.callProc(instr.operands[0]!, []) },
    }
}

describe("extension hook — a call-shaped op actually invokes its callee", () =>
{
    test("validates (folded into the call graph) and executes the nested call", () =>
    {
        const ext = callShapedExtension()
        const program: RtlProgram = {
            procedures: [
                { argCount: 0, body: [extInstr("EXT_CALL", [1]), bare("RETURN")] }, // entry: ext_call(helper)
                { argCount: 0, body: [{ op: "CONST", imm: 99 }, bare("RETURN")] }, // helper: return 99;
            ],
        }

        const stats = validateProgram(program, ext)
        assert.equal(stats.totalDepth, 0) // neither procedure ever pushes to TOS

        const result = run(program, ext)
        assert.equal(result.ok, true)
        assert.equal(result.acc, 99) // proves callProc's return value actually reaches EXT_CALL's acc
    })
})

describe("extension hook — absent extension leaves every stage unaffected", () =>
{
    test("an EXT instruction with no matching effect declaration is rejected by the validator", () =>
    {
        const program: RtlProgram = { procedures: [{ argCount: 0, body: [extInstr("UNKNOWN", []), bare("RETURN")] }] }
        assert.throws(() => validateProgram(program), /no effect declaration registered/)
    })

    test("an EXT instruction with no registered exec throws at VM runtime", () =>
    {
        const program: RtlProgram = { procedures: [{ argCount: 0, body: [extInstr("DOUBLE_REG", [0]), bare("RETURN")] }] }
        assert.throws(() => run(program), /no extension registered to execute it/)
    })

    test("encoding an EXT instruction with no registered codec throws", () =>
    {
        assert.throws(() => encodeInstr(extInstr("DOUBLE_REG", [0])), /no registered extension codec/)
    })

    test("decoding an extension opcode byte with no registered codec throws", () =>
    {
        assert.throws(() => decodeBody(Uint8Array.from([128, 3])), /no extension mechanism registered/)
    })
})

describe("Procedure/RtlProc header — opaque data, untouched by the core", () =>
{
    test("carried through lowering unchanged", () =>
    {
        const header = { abiKind: "CODEC_ENCODER" }
        const entry = proc([], ir`return 1;`, header)

        const program = lowerProgram(entry)
        assert.equal(program.procedures[0]!.header, header)
    })
})
